<?php
return [
	"string" => "Der Wert von :attribute ist kein Text!",
	"string_min_length" => "Der Wert von :attribute muss mindestens :length Zeichen lang sein!",
	"string_max_length" => "Der Wert von :attribute darf maximal :length Zeichen lang sein!",
	"int" => "Der Wert von :attribute ist keine ganze Zahl!",
	"float" => "Der Wert von :attribute ist keine Zahl!",
	"numeric" => "Der Wert von :attribute ist keine Zahl!",
	"array" => "Der Wert von :attribute ist kein Array!",
	"required" => "Das Feld :attribute ist erforderlich!",
	"in" => "Der Wert von :attribute ist ungültig! (:values)",
	"invalid" => "Ungültiger Wert: :attribute!",
	"date" => "Ungültiges Datum: :attribute!",
	"contains" => "Der Wert von :attribute muss den Wert \":value\" enthalten!",
	"eq" => "Der Wert von :attribute muss gleich :value sein!",
	"gt" => "Der Wert von :attribute muss größer als :value sein!",
	"gte" => "Der Wert von :attribute muss größer oder gleich :value sein!",
	"lt" => "Der Wert von :attribute muss kleiner als :value sein!",
	"lte" => "Der Wert von :attribute muss kleiner oder gleich :value sein!",
	"unique" => "Der Wert von :attribute ist bereits vergeben!",
	"invalid_file" => "Ungültige Datei: :attribute!",
	"max_filesize" => "Die Größe von :attribute darf maximal :size :unit betragen!",
	"file_extension" => "Die Dateierweiterung von :attribute ist nicht erlaubt! (:extensions)",
	"mime_type" => "Der Wert von :attribute darf nur eines der folgenden Dateiformate sein: (:mimeTypes)!",
	"email" => "Ungültige E-Mail-Adresse: :attribute!",
];