<?php
return [
	"string" => "A(z) :attribute értéke nem szöveg!",
	"string_min_length" => "A(z) :attribute értékének minimum :length karakternek kell lennie!",
	"string_max_length" => "The :attribute maximum :length karaktert tartalmazhat!",
	"int" => "A(z) :attribute nem egész számot tartalmaz!",
	"float" => "A(z) :attribute nem számot tartalmaz!",
	"numeric" => "A(z) :attribute nem számot tartalmaz!",
	"array" => "A(z) :attribute nem tömböt tartalmaz!",
	"required" => "Kötelező mező: :attribute!",
	"in" => "A(z) :attribute értéke helytelen! (:values)",
	"invalid" => "Helytelen érték: :attribute!",
	"date" => "Helytelen dátum: :attribute!",
	"contains" => "A(z) :attribute értékének tartalmaznia kell a(z) \":value\" értéket!",
	"eq" => "A(z) :attribute értékének egyeznie kell a következővel :value!",
	"gt" => "A(z) :attribute nagyobb kell, hogy legyen, mint :value!",
	"gte" => "A(z) :attribute nagyobb vagy egyenlő kell, hogy legyen, mint :value!",
	"lt" => "A(z) :attribute kisebbnek kell, hogy legyen, mint :value!",
	"lte" => "A(z) :attribute kisebbnek vagy egyenlőnek kell, hogy legyen, mint :value!",
	"unique" => "A(z) :attribute már foglalt!",
	"invalid_file" => "Helytelen fájl: :attribute!",
	"max_filesize" => "A(z) :attribute mérete maximum :size :unit lehet!",
	"file_extension" => "A(z) :attribute kiterjesztése nem engedélyezett! (:extensions)",
	"mime_type" => "A(z) :attribute kizárólag az alábbi fájlformátumok egyike lehet: (:mimeTypes)!",
	"email" => "Helytelen e-mail cím: :attribute!",
];
