<?php
return [
	"string" => "Hodnota :attribute nie je text!",
	"string_min_length" => "Hodnota :attribute musí mať minimálne :length znakov!",
	"string_max_length" => "Hodnota :attribute môže mať maximálne :length znakov!",
	"int" => "Hodnota :attribute nie je celé číslo!",
	"float" => "Hodnota :attribute nie je číslo!",
	"numeric" => "Hodnota :attribute nie je číslo!",
	"array" => "Hodnota :attribute nie je pole!",
	"required" => "Pole :attribute je povinné!",
	"in" => "Hodnota :attribute je neplatná! (:values)",
	"invalid" => "Neplatná hodnota: :attribute!",
	"date" => "Neplatný dátum: :attribute!",
	"contains" => "Hodnota :attribute musí obsahovať hodnotu \":value\"!",
	"eq" => "Hodnota :attribute musí byť rovná :value!",
	"gt" => "Hodnota :attribute musí byť väčšia ako :value!",
	"gte" => "Hodnota :attribute musí byť väčšia alebo rovná :value!",
	"lt" => "Hodnota :attribute musí byť menšia ako :value!",
	"lte" => "Hodnota :attribute musí byť menšia alebo rovná :value!",
	"unique" => "Hodnota :attribute je už obsadená!",
	"invalid_file" => "Neplatný súbor: :attribute!",
	"max_filesize" => "Veľkosť :attribute môže byť maximálne :size :unit!",
	"file_extension" => "Prípona súboru :attribute nie je povolená! (:extensions)",
	"mime_type" => "Hodnota :attribute môže byť iba jeden z nasledujúcich formátov súborov: (:mimeTypes)!",
	"email" => "Neplatná e-mailová adresa: :attribute!",
];